const eventData = [
    { date: "1587", event: "Elekcja Zygmunta III Wazy" },
    { date: "1596", event: "Unia brzeska" },
    { date: "1605", event: "Bitwa pod Kircholmem" },
    { date: "1606", event: "Rokosz Zebrzydowskiego / rokosz sandomierski" },
    { date: "1610", event: "Bitwa pod Kłuszynem" },
    { date: "1619", event: "Rozejm w Dywilinie z Rosją" },
    { date: "1620", event: "Bitwa pod Cecorą" },
    { date: "1621", event: "Oblężenie Chocimia przez wojska tureckie" },
    { date: "1627", event: "Bitwa pod Oliwą" },
    { date: "1629", event: "Rozejm w Starym Targu ze Szwecją" },
    { date: "1632", event: "Śmierć Zygmunta III" },
    { date: "1632", event: "Elekcja Władysława IV" },
    { date: "1634", event: "Pokój w Polanowie z Rosją" },
    { date: "1635", event: "Rozejm w Sztumskiej Wsi ze Szwecją" },
    { date: "1648", event: "Wybuch powstania Bohdana Chmielnickiego" },
    { date: "1648", event: "Koronacja Jana Kazimierza" },
    { date: "1649", event: "Ugoda zborowska z Kozakami" },
    { date: "1651", event: "Bitwa pod Beresteczkiem" },
    { date: "1654", event: "Ugoda perejasławska" },
    { date: "1655", event: "Początek potopu szwedzkiego" },
    { date: "1658", event: "Unia w Hadziaczu" },
    { date: "1660", event: "Zawarcie pokoju oliwskiego ze Szwecją" },
    { date: "1665", event: "Rokosz Lubomirskiego" },
    { date: "1667", event: "Rozejm w Andruszowie z Rosją" },
    { date: "1672", event: "Zawarcie traktatu w Buczaczu z Turcją" },
    { date: "1683", event: "Odsiecz wiedeńska" },
    { date: "1686", event: "Pokój Grzymułtowskiego z Rosją" },
    { date: "1697", event: "Elekcja Augusta II Mocnego" },
    { date: "1699", event: "Pokój w Karłowicach z Turcją" }
];
